# -*- coding: utf-8 -*-
"""sugarcane.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_J1YES5cNQlLffEq_WgbAdgUxJjEoRH
"""

# YOLOv8 Sugarcane Bud Detection Training
# This notebook trains a YOLOv8 model for sugarcane bud detection

# ============================================
# 1. Install Required Libraries
# ============================================
!pip install ultralytics roboflow -q

# ============================================
# 2. Import Libraries
# ============================================
from ultralytics import YOLO
from roboflow import Roboflow
import os
from pathlib import Path
import shutil

# ============================================
# 3. Enable GPU Check
# ============================================
print("⚠️ IMPORTANT: Enable GPU in Colab!")
print("Go to: Runtime → Change runtime type → Hardware accelerator → GPU (T4)")
print("=" * 60)

import torch
if torch.cuda.is_available():
    device = 0
    print(f"✓ GPU: {torch.cuda.get_device_name(0)}")
else:
    device = 'cpu'
    print("⚠️ WARNING: Training on CPU will be VERY slow!")
    print("Enable GPU: Runtime → Change runtime type → GPU")

# ============================================
# 4. Download Dataset from Roboflow
# ============================================
print("\n📥 Downloading dataset from Roboflow Universe...")

# PASTE YOUR ROBOFLOW CODE HERE

from roboflow import Roboflow
rf = Roboflow(api_key="cqIVaEBvoItTYupdhBDA")
project = rf.workspace("mrdeveloper").project("sugar-cane-bud-detection-mmuhw")
version = project.version(1)
dataset = version.download("yolov8")

# Get dataset path automatically
dataset_path = dataset.location
print(f"✓ Dataset downloaded to: {dataset_path}")

# ============================================
# 5. Verify Dataset Structure
# ============================================
print("\n📂 Dataset structure:")
for root, dirs, files in os.walk(dataset_path):
    level = root.replace(dataset_path, '').count(os.sep)
    if level > 2:
        continue
    indent = ' ' * 2 * level
    print(f'{indent}{os.path.basename(root)}/')
    subindent = ' ' * 2 * (level + 1)
    for file in files[:3]:
        print(f'{subindent}{file}')
    if len(files) > 3:
        print(f'{subindent}... and {len(files) - 3} more files')

# ============================================
# 6. Verify data.yaml
# ============================================
data_yaml_path = os.path.join(dataset_path, 'data.yaml')

if os.path.exists(data_yaml_path):
    print(f"\n✓ Found data.yaml at: {data_yaml_path}")
    with open(data_yaml_path, 'r') as f:
        print("\ndata.yaml contents:")
        print(f.read())
else:
    print("\n❌ data.yaml not found!")
    raise FileNotFoundError("data.yaml missing from dataset")

# ============================================
# 7. Initialize YOLOv8 Model
# ============================================
model = YOLO('yolov8n.pt')
print("\n✓ Model initialized (YOLOv8 Nano)")

# ============================================
# 8. Train the Model
# ============================================
print("\n" + "=" * 50)
print("STARTING TRAINING")
print("=" * 50)

results = model.train(
    data=data_yaml_path,
    epochs=30,
    imgsz=640,
    batch=16,
    device=device,
    patience=5,
    save=True,
    project='sugarcane_bud_detection',
    name='yolov8_15epochs',
    verbose=True,
    plots=True
)

print("\n" + "=" * 50)
print("✓ TRAINING COMPLETED!")
print("=" * 50)

# ============================================
# 9. Evaluate the Model
# ============================================
print("\nEvaluating model...")
metrics = model.val()

print("\n📊 Validation Metrics:")
print(f"  mAP50: {metrics.box.map50:.4f}")
print(f"  mAP50-95: {metrics.box.map:.4f}")
print(f"  Precision: {metrics.box.mp:.4f}")
print(f"  Recall: {metrics.box.mr:.4f}")

# ============================================
# 10. Save and Download Model
# ============================================
best_model_path = 'sugarcane_bud_detection/yolov8_15epochs/weights/best.pt'
last_model_path = 'sugarcane_bud_detection/yolov8_15epochs/weights/last.pt'

print(f"\n✓ Best model: {best_model_path}")
print(f"✓ Last model: {last_model_path}")

# Copy to /content/ for easy download
shutil.copy(best_model_path, '/content/best_bud_detection.pt')
shutil.copy(last_model_path, '/content/last_bud_detection.pt')

print("\n✓ Models ready for download:")
print("  - /content/best_bud_detection.pt")
print("  - /content/last_bud_detection.pt")

# ============================================
# 11. Test Inference
# ============================================
print("\n🧪 Testing inference...")

test_images_dir = os.path.join(dataset_path, 'valid/images')
if os.path.exists(test_images_dir):
    test_images = [f for f in os.listdir(test_images_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]
    if test_images:
        test_image = os.path.join(test_images_dir, test_images[0])

        best_model = YOLO(best_model_path)
        results = best_model(test_image)

        results[0].save('/content/test_prediction.jpg')
        print(f"✓ Test prediction saved: /content/test_prediction.jpg")

        from IPython.display import Image, display
        display(Image('/content/test_prediction.jpg'))

print("\n" + "=" * 50)
print("🎉 ALL DONE! Model ready for bud detection")
print("=" * 50)

# ============================================
# 12. Real-Time Webcam Detection
# ============================================

# Import required libraries (if running in separate cell)
from ultralytics import YOLO
from IPython.display import display, Javascript, Image as IPImage
from google.colab.output import eval_js
from base64 import b64decode, b64encode
import cv2
import numpy as np
from PIL import Image
import io
import time

print("📸 Setting up webcam detection...")

# JavaScript code to access webcam
def setup_webcam():
    js = Javascript('''
    async function captureCamera() {
      const div = document.createElement('div');
      document.body.appendChild(div);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext('2d');

      return {video, canvas, ctx, stream};
    }
    ''')
    display(js)

def webcam_stream():
    """Continuous webcam stream with detection"""
    js = Javascript('''
    async function startStream() {
      const div = document.createElement('div');
      document.body.appendChild(div);

      const video = document.createElement('video');
      video.style.display = 'block';
      video.width = 640;
      video.height = 480;

      const canvas = document.createElement('canvas');
      canvas.width = 640;
      canvas.height = 480;
      div.appendChild(canvas);

      const stream = await navigator.mediaDevices.getUserMedia({video: {width: 640, height: 480}});
      video.srcObject = stream;
      await video.play();

      const ctx = canvas.getContext('2d');

      window.videoElement = video;
      window.canvasElement = canvas;
      window.ctxElement = ctx;

      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      return "Stream started";
    }
    ''')
    display(js)
    return eval_js('startStream()')

def get_frame():
    """Get current frame from stream"""
    js = Javascript('''
    async function getFrame() {
      const video = window.videoElement;
      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(video, 0, 0);
      return canvas.toDataURL('image/jpeg', 0.8);
    }
    ''')

    try:
        data = eval_js('getFrame()')
        binary = b64decode(data.split(',')[1])
        img = Image.open(io.BytesIO(binary))
        return cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    except:
        return None

def display_frame(img_array):
    """Display processed frame back to canvas"""
    _, buffer = cv2.imencode('.jpg', img_array)
    img_base64 = b64encode(buffer).decode('utf-8')

    js = Javascript(f'''
    async function displayFrame() {{
      const img = new Image();
      img.src = 'data:image/jpeg;base64,{img_base64}';
      await img.decode();

      const ctx = window.ctxElement;
      ctx.drawImage(img, 0, 0, window.canvasElement.width, window.canvasElement.height);
    }}
    displayFrame();
    ''')
    display(js)

# Load your trained model
print("🔄 Loading trained model...")
model = YOLO('/content/best_bud_detection.pt')
print("✓ Model loaded successfully")

# Start webcam stream
print("🚀 Starting real-time bud detection...")
print("Press 'Stop' button in Colab to exit")
print("=" * 60)

webcam_stream()

try:
    frame_count = 0
    while True:
        frame = get_frame()

        if frame is not None:
            # Run YOLOv8 detection
            results = model(frame, conf=0.5, verbose=False)

            # Draw bounding boxes with RED color
            annotated_frame = results[0].plot(
                line_width=2,
                font_size=1,
                labels=True,
                conf=True
            )

            # Display frame with detections
            display_frame(annotated_frame)

            frame_count += 1
            if frame_count % 30 == 0:
                print(f"✓ Processed {frame_count} frames...")

        time.sleep(0.1)

except KeyboardInterrupt:
    print("\n✓ Detection stopped")
    print(f"Total frames processed: {frame_count}")

# ============================================
# 12. Real-Time Webcam Detection with Arduino Control
# ============================================

# Install required libraries
!pip install ultralytics roboflow -q
!pip install pyserial -q

# Import required libraries
from ultralytics import YOLO
from IPython.display import display, Javascript, HTML
from google.colab.output import eval_js
from google.colab import output
from base64 import b64decode, b64encode
import cv2
import numpy as np
from PIL import Image
import io
import time
import serial

print("📸 Setting up webcam detection with Arduino control...")

# ============================================
# Arduino Setup (Optional - if Arduino connected)
# ============================================
ARDUINO_CONNECTED = False  # Set to True if Arduino is connected

try:
    # Change COM port to match your Arduino (e.g., 'COM3', '/dev/ttyUSB0')
    arduino = serial.Serial('COM3', 9600, timeout=1)
    time.sleep(2)  # Wait for Arduino to initialize
    ARDUINO_CONNECTED = True
    print("✓ Arduino connected on COM3")
except:
    print("⚠️ Arduino not connected - detection will work without it")
    arduino = None

# ============================================
# Webcam Stream with Visible Display
# ============================================

def start_webcam_with_display():
    """Start webcam with live video display"""
    js = Javascript('''
    async function startVideoStream() {
      const div = document.createElement('div');
      div.style.textAlign = 'center';
      document.body.appendChild(div);

      // Create video element (hidden - we'll use canvas)
      const video = document.createElement('video');
      video.style.display = 'none';
      video.width = 640;
      video.height = 480;

      // Create canvas for display
      const canvas = document.createElement('canvas');
      canvas.width = 640;
      canvas.height = 480;
      canvas.style.border = '2px solid #00ff00';
      canvas.style.borderRadius = '10px';
      div.appendChild(canvas);

      // Add detection counter display
      const counterDiv = document.createElement('div');
      counterDiv.id = 'detectionCounter';
      counterDiv.style.fontSize = '24px';
      counterDiv.style.fontWeight = 'bold';
      counterDiv.style.color = '#00ff00';
      counterDiv.style.marginTop = '10px';
      counterDiv.innerHTML = 'Detections: 0 | Status: Waiting...';
      div.appendChild(counterDiv);

      // Get webcam stream
      const stream = await navigator.mediaDevices.getUserMedia({
        video: {width: 640, height: 480}
      });

      video.srcObject = stream;
      await video.play();

      const ctx = canvas.getContext('2d');

      // Store globally
      window.videoElement = video;
      window.canvasElement = canvas;
      window.ctxElement = ctx;
      window.streamActive = true;

      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      return "Stream started";
    }
    ''')
    display(js)
    return eval_js('startVideoStream()')

def get_frame():
    """Get current frame from webcam"""
    js = Javascript('''
    async function captureFrame() {
      if (!window.streamActive) return null;

      const video = window.videoElement;
      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(video, 0, 0);
      return canvas.toDataURL('image/jpeg', 0.8);
    }
    ''')

    try:
        data = eval_js('captureFrame()')
        if data:
            binary = b64decode(data.split(',')[1])
            img = Image.open(io.BytesIO(binary))
            return cv2.cvtColor(np.array(img), cv2.COLOR_RGB2BGR)
    except:
        pass
    return None

def display_frame(img_array, num_detections, fps):
    """Display processed frame with detections on canvas"""
    # Encode image
    _, buffer = cv2.imencode('.jpg', img_array)
    img_base64 = b64encode(buffer).decode('utf-8')

    # Update canvas and counter
    js = Javascript(f'''
    async function updateDisplay() {{
      const img = new Image();
      img.src = 'data:image/jpeg;base64,{img_base64}';
      await img.decode();

      const ctx = window.ctxElement;
      ctx.drawImage(img, 0, 0, window.canvasElement.width, window.canvasElement.height);

      // Update counter
      const counter = document.getElementById('detectionCounter');
      if (counter) {{
        const status = {num_detections} > 0 ? '🟢 BUD DETECTED!' : '⚪ Scanning...';
        counter.innerHTML = `Detections: {num_detections} | FPS: {fps:.1f} | ${{status}}`;
        counter.style.color = {num_detections} > 0 ? '#ff0000' : '#00ff00';
      }}
    }}
    updateDisplay();
    ''')
    display(js)

def send_arduino_signal(num_buds):
    """Send signal to Arduino when bud is detected"""
    if ARDUINO_CONNECTED and arduino:
        try:
            # Send '1' when bud detected, '0' when no bud
            signal = '1' if num_buds > 0 else '0'
            arduino.write(signal.encode())

            # Read response from Arduino (optional)
            if arduino.in_waiting > 0:
                response = arduino.readline().decode('utf-8').strip()
                return response
        except Exception as e:
            print(f"Arduino error: {e}")
    return None

# ============================================
# Main Detection Loop
# ============================================

# Load trained model
print("🔄 Loading trained model...")
model = YOLO('/content/best_bud_detection.pt')
print("✓ Model loaded successfully")

# Start webcam
print("🚀 Starting real-time bud detection...")
print("=" * 60)
start_webcam_with_display()

# Detection loop
try:
    frame_count = 0
    detection_count = 0
    start_time = time.time()
    last_detection_state = False

    while True:
        # Get frame
        frame = get_frame()

        if frame is not None:
            # Run detection
            results = model(frame, conf=0.5, verbose=False)

            # Count detections
            num_buds = len(results[0].boxes)
            detection_count += num_buds

            # Draw bounding boxes (RED boxes for detected buds)
            annotated_frame = results[0].plot(
                line_width=3,
                font_size=1.5,
                labels=True,
                conf=True
            )

            # Calculate FPS
            frame_count += 1
            elapsed_time = time.time() - start_time
            fps = frame_count / elapsed_time if elapsed_time > 0 else 0

            # Display frame with detection info
            display_frame(annotated_frame, num_buds, fps)

            # Send signal to Arduino when bud detected
            if num_buds > 0:
                if not last_detection_state:  # Only send on new detection
                    arduino_response = send_arduino_signal(num_buds)
                    print(f"🔴 BUD DETECTED! Count: {num_buds}")
                    if arduino_response:

                        print(f"   Arduino: {arduino_response}")
                last_detection_state = True
            else:
                if last_detection_state:  # Send clear signal
                    send_arduino_signal(0)
                last_detection_state = False

            # Progress update every 30 frames
            if frame_count % 30 == 0:
                print(f"✓ Frames: {frame_count} | Detections: {detection_count} | FPS: {fps:.1f}")

        time.sleep(0.05)  # 20 FPS target

except KeyboardInterrupt:
    print("\n✓ Detection stopped")
    print(f"Total frames: {frame_count}")
    print(f"Total detections: {detection_count}")
    if ARDUINO_CONNECTED:
        arduino.close()
        print("✓ Arduino connection closed")

